// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.newtrip.live_photo_gallery

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 相册权限状态。门面层映射为公开的
 * `"authorized" | "limited" | "denied" | "notDetermined"` 字符串。
 */
enum class PgPermissionStatus(val raw: Int) {
  AUTHORIZED(0),
  LIMITED(1),
  DENIED(2),
  NOT_DETERMINED(3);

  companion object {
    fun ofRaw(raw: Int): PgPermissionStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** 媒体类型过滤（对应公开的 [MediaFilter]） */
enum class PgMediaFilter(val raw: Int) {
  ALL(0),
  IMAGE_ONLY(1),
  VIDEO_ONLY(2),
  LIVE_PHOTO_ONLY(3);

  companion object {
    fun ofRaw(raw: Int): PgMediaFilter? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** 单个媒体条目的类型（对应公开 API 的 `"image" | "video" | "livePhoto"`） */
enum class PgMediaType(val raw: Int) {
  IMAGE(0),
  VIDEO(1),
  LIVE_PHOTO(2);

  companion object {
    fun ofRaw(raw: Int): PgMediaType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** 预览资源来源（对应公开 API 的 `"local" | "network"`） */
enum class PgAssetSource(val raw: Int) {
  LOCAL(0),
  NETWORK(1);

  companion object {
    fun ofRaw(raw: Int): PgAssetSource? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** 导出格式（对应公开 API 的 `"image" | "video" | "livePhotoVideo"`） */
enum class PgExportFormat(val raw: Int) {
  IMAGE(0),
  VIDEO(1),
  LIVE_PHOTO_VIDEO(2);

  companion object {
    fun ofRaw(raw: Int): PgExportFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 保存网络图片失败的原因（对应公开的 [DownloadErrorCode]）。
 * 此前 Android 发 `"NETWORK_ERROR"` 字符串、iOS 发另一套、Dart 侧再 fromString，
 * 三处任意一处笔误都会静默退化成 `unknown`——改为枚举后是编译期错误。
 */
enum class PgDownloadErrorCode(val raw: Int) {
  PERMISSION_DENIED(0),
  NETWORK_ERROR(1),
  SAVE_FAILED(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): PgDownloadErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * 裁剪配置（对应公开的 [CropConfig]）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgCropConfig (
  val aspectRatioX: Double,
  val aspectRatioY: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgCropConfig {
      val aspectRatioX = pigeonVar_list[0] as Double
      val aspectRatioY = pigeonVar_list[1] as Double
      return PgCropConfig(aspectRatioX, aspectRatioY)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      aspectRatioX,
      aspectRatioY,
    )
  }
}

/**
 * 选择器配置（对应公开的 [PickerConfig]）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgPickerConfig (
  val isDarkMode: Boolean,
  val maxCount: Long,
  val enableVideo: Boolean,
  val enableLivePhoto: Boolean,
  val showRadio: Boolean,
  /** -1 = 无限制 */
  val maxVideoCount: Long,
  /** 秒，0 = 无限制 */
  val videoMaxDuration: Double,
  val filterConfig: PgMediaFilter,
  val cropConfig: PgCropConfig? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgPickerConfig {
      val isDarkMode = pigeonVar_list[0] as Boolean
      val maxCount = pigeonVar_list[1] as Long
      val enableVideo = pigeonVar_list[2] as Boolean
      val enableLivePhoto = pigeonVar_list[3] as Boolean
      val showRadio = pigeonVar_list[4] as Boolean
      val maxVideoCount = pigeonVar_list[5] as Long
      val videoMaxDuration = pigeonVar_list[6] as Double
      val filterConfig = pigeonVar_list[7] as PgMediaFilter
      val cropConfig = pigeonVar_list[8] as PgCropConfig?
      return PgPickerConfig(isDarkMode, maxCount, enableVideo, enableLivePhoto, showRadio, maxVideoCount, videoMaxDuration, filterConfig, cropConfig)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isDarkMode,
      maxCount,
      enableVideo,
      enableLivePhoto,
      showRadio,
      maxVideoCount,
      videoMaxDuration,
      filterConfig,
      cropConfig,
    )
  }
}

/**
 * 缩略图在屏幕中的位置（逻辑像素），用于飞入/飞回转场
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgRect (
  val x: Double,
  val y: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgRect {
      val x = pigeonVar_list[0] as Double
      val y = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      return PgRect(x, y, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      x,
      y,
      width,
      height,
    )
  }
}

/**
 * 传给 previewAssets 的单个资源（对应公开的 [AssetInput]）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgAssetInput (
  val type: PgAssetSource,
  val assetId: String? = null,
  val url: String? = null,
  val mediaType: PgMediaType? = null,
  val videoUrl: String? = null,
  /** 视频时长（秒） */
  val duration: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgAssetInput {
      val type = pigeonVar_list[0] as PgAssetSource
      val assetId = pigeonVar_list[1] as String?
      val url = pigeonVar_list[2] as String?
      val mediaType = pigeonVar_list[3] as PgMediaType?
      val videoUrl = pigeonVar_list[4] as String?
      val duration = pigeonVar_list[5] as Double?
      return PgAssetInput(type, assetId, url, mediaType, videoUrl, duration)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      assetId,
      url,
      mediaType,
      videoUrl,
      duration,
    )
  }
}

/**
 * previewAssets 的完整入参
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgPreviewRequest (
  val assets: List<PgAssetInput>,
  val initialIndex: Long,
  val sourceFrame: PgRect,
  val selectedAssetIds: List<String>,
  val config: PgPickerConfig,
  val showDownloadButton: Boolean,
  /** 空串 = 不额外建相册（iOS）/ 用 App 名（Android） */
  val saveAlbumName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgPreviewRequest {
      val assets = pigeonVar_list[0] as List<PgAssetInput>
      val initialIndex = pigeonVar_list[1] as Long
      val sourceFrame = pigeonVar_list[2] as PgRect
      val selectedAssetIds = pigeonVar_list[3] as List<String>
      val config = pigeonVar_list[4] as PgPickerConfig
      val showDownloadButton = pigeonVar_list[5] as Boolean
      val saveAlbumName = pigeonVar_list[6] as String
      return PgPreviewRequest(assets, initialIndex, sourceFrame, selectedAssetIds, config, showDownloadButton, saveAlbumName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      assets,
      initialIndex,
      sourceFrame,
      selectedAssetIds,
      config,
      showDownloadButton,
      saveAlbumName,
    )
  }
}

/**
 * 返回的单个媒体条目（对应公开的 [MediaItem]）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgMediaItem (
  val assetId: String,
  val mediaType: PgMediaType,
  val thumbnailPath: String,
  /** 秒，仅 video 有值 */
  val duration: Double? = null,
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgMediaItem {
      val assetId = pigeonVar_list[0] as String
      val mediaType = pigeonVar_list[1] as PgMediaType
      val thumbnailPath = pigeonVar_list[2] as String
      val duration = pigeonVar_list[3] as Double?
      val width = pigeonVar_list[4] as Long
      val height = pigeonVar_list[5] as Long
      return PgMediaItem(assetId, mediaType, thumbnailPath, duration, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      assetId,
      mediaType,
      thumbnailPath,
      duration,
      width,
      height,
    )
  }
}

/**
 * pickAssets / previewAssets 的返回（对应公开的 [PickResult]）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgPickResult (
  val items: List<PgMediaItem>,
  val isOriginalPhoto: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgPickResult {
      val items = pigeonVar_list[0] as List<PgMediaItem>
      val isOriginalPhoto = pigeonVar_list[1] as Boolean
      return PgPickResult(items, isOriginalPhoto)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      isOriginalPhoto,
    )
  }
}

/**
 * 保存网络图片的结果事件（对应公开的 [DownloadResult] sealed 家族）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgDownloadResultEvent (
  val url: String,
  val success: Boolean,
  /** 成功时的 assetId（Android: MediaStore URI；iOS: PHAsset localIdentifier） */
  val assetId: String? = null,
  /** 失败时的错误码 */
  val errorCode: PgDownloadErrorCode? = null,
  /** 失败时的可读描述 */
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgDownloadResultEvent {
      val url = pigeonVar_list[0] as String
      val success = pigeonVar_list[1] as Boolean
      val assetId = pigeonVar_list[2] as String?
      val errorCode = pigeonVar_list[3] as PgDownloadErrorCode?
      val errorMessage = pigeonVar_list[4] as String?
      return PgDownloadResultEvent(url, success, assetId, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      success,
      assetId,
      errorCode,
      errorMessage,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgPermissionStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgMediaFilter.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgMediaType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgAssetSource.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgExportFormat.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgDownloadErrorCode.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgCropConfig.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgPickerConfig.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgRect.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgAssetInput.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgPreviewRequest.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgMediaItem.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgPickResult.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgDownloadResultEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PgPermissionStatus -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PgMediaFilter -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is PgMediaType -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is PgAssetSource -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is PgExportFormat -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is PgDownloadErrorCode -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is PgCropConfig -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PgPickerConfig -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PgRect -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PgAssetInput -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PgPreviewRequest -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PgMediaItem -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is PgPickResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is PgDownloadResultEvent -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LivePhotoGalleryHostApi {
  /** 查询/申请相册权限 */
  fun requestPermission(callback: (Result<PgPermissionStatus>) -> Unit)
  /** 打开相册选择器；返回 null 表示用户取消 */
  fun pickAssets(config: PgPickerConfig, callback: (Result<PgPickResult?>) -> Unit)
  /** 预览资源列表（本地 & 网络混合）；返回 null 表示用户取消 */
  fun previewAssets(request: PgPreviewRequest, callback: (Result<PgPickResult?>) -> Unit)
  /** 返回本地缩略图路径 */
  fun getThumbnail(assetId: String, width: Double, height: Double, callback: (Result<String?>) -> Unit)
  /** 导出资源原文件到临时目录，返回本地路径 */
  fun exportAsset(assetId: String, format: PgExportFormat, callback: (Result<String?>) -> Unit)
  /** 清理插件产生的临时文件 */
  fun cleanupTempFiles(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by LivePhotoGalleryHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LivePhotoGalleryHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LivePhotoGalleryHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPermission{ result: Result<PgPermissionStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.pickAssets$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as PgPickerConfig
            api.pickAssets(configArg) { result: Result<PgPickResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.previewAssets$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PgPreviewRequest
            api.previewAssets(requestArg) { result: Result<PgPickResult?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.getThumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdArg = args[0] as String
            val widthArg = args[1] as Double
            val heightArg = args[2] as Double
            api.getThumbnail(assetIdArg, widthArg, heightArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.exportAsset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdArg = args[0] as String
            val formatArg = args[1] as PgExportFormat
            api.exportAsset(assetIdArg, formatArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.cleanupTempFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cleanupTempFiles{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class LivePhotoGalleryFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LivePhotoGalleryFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** 预览页保存网络图片完成（成功或失败） */
  fun onDownloadResult(eventArg: PgDownloadResultEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** 预览页下载进度（0.0 ~ 1.0） */
  fun onDownloadProgress(urlArg: String, progressArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(urlArg, progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** 用户尝试超出最大选择数量 */
  fun onMaxCountReached(maxCountArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onMaxCountReached$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(maxCountArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
