// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 相册权限状态。门面层映射为公开的
/// `"authorized" | "limited" | "denied" | "notDetermined"` 字符串。
enum PgPermissionStatus: Int {
  case authorized = 0
  case limited = 1
  case denied = 2
  case notDetermined = 3
}

/// 媒体类型过滤（对应公开的 [MediaFilter]）
enum PgMediaFilter: Int {
  case all = 0
  case imageOnly = 1
  case videoOnly = 2
  case livePhotoOnly = 3
}

/// 单个媒体条目的类型（对应公开 API 的 `"image" | "video" | "livePhoto"`）
enum PgMediaType: Int {
  case image = 0
  case video = 1
  case livePhoto = 2
}

/// 预览资源来源（对应公开 API 的 `"local" | "network"`）
enum PgAssetSource: Int {
  case local = 0
  case network = 1
}

/// 导出格式（对应公开 API 的 `"image" | "video" | "livePhotoVideo"`）
enum PgExportFormat: Int {
  case image = 0
  case video = 1
  case livePhotoVideo = 2
}

/// 保存网络图片失败的原因（对应公开的 [DownloadErrorCode]）。
/// 此前 Android 发 `"NETWORK_ERROR"` 字符串、iOS 发另一套、Dart 侧再 fromString，
/// 三处任意一处笔误都会静默退化成 `unknown`——改为枚举后是编译期错误。
enum PgDownloadErrorCode: Int {
  case permissionDenied = 0
  case networkError = 1
  case saveFailed = 2
  case unknown = 3
}

/// 裁剪配置（对应公开的 [CropConfig]）
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgCropConfig {
  var aspectRatioX: Double
  var aspectRatioY: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgCropConfig? {
    let aspectRatioX = pigeonVar_list[0] as! Double
    let aspectRatioY = pigeonVar_list[1] as! Double

    return PgCropConfig(
      aspectRatioX: aspectRatioX,
      aspectRatioY: aspectRatioY
    )
  }
  func toList() -> [Any?] {
    return [
      aspectRatioX,
      aspectRatioY,
    ]
  }
}

/// 选择器配置（对应公开的 [PickerConfig]）
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgPickerConfig {
  var isDarkMode: Bool
  var maxCount: Int64
  var enableVideo: Bool
  var enableLivePhoto: Bool
  var showRadio: Bool
  /// -1 = 无限制
  var maxVideoCount: Int64
  /// 秒，0 = 无限制
  var videoMaxDuration: Double
  var filterConfig: PgMediaFilter
  var cropConfig: PgCropConfig? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgPickerConfig? {
    let isDarkMode = pigeonVar_list[0] as! Bool
    let maxCount = pigeonVar_list[1] as! Int64
    let enableVideo = pigeonVar_list[2] as! Bool
    let enableLivePhoto = pigeonVar_list[3] as! Bool
    let showRadio = pigeonVar_list[4] as! Bool
    let maxVideoCount = pigeonVar_list[5] as! Int64
    let videoMaxDuration = pigeonVar_list[6] as! Double
    let filterConfig = pigeonVar_list[7] as! PgMediaFilter
    let cropConfig: PgCropConfig? = nilOrValue(pigeonVar_list[8])

    return PgPickerConfig(
      isDarkMode: isDarkMode,
      maxCount: maxCount,
      enableVideo: enableVideo,
      enableLivePhoto: enableLivePhoto,
      showRadio: showRadio,
      maxVideoCount: maxVideoCount,
      videoMaxDuration: videoMaxDuration,
      filterConfig: filterConfig,
      cropConfig: cropConfig
    )
  }
  func toList() -> [Any?] {
    return [
      isDarkMode,
      maxCount,
      enableVideo,
      enableLivePhoto,
      showRadio,
      maxVideoCount,
      videoMaxDuration,
      filterConfig,
      cropConfig,
    ]
  }
}

/// 缩略图在屏幕中的位置（逻辑像素），用于飞入/飞回转场
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgRect {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgRect? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return PgRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
}

/// 传给 previewAssets 的单个资源（对应公开的 [AssetInput]）
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgAssetInput {
  var type: PgAssetSource
  var assetId: String? = nil
  var url: String? = nil
  var mediaType: PgMediaType? = nil
  var videoUrl: String? = nil
  /// 视频时长（秒）
  var duration: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgAssetInput? {
    let type = pigeonVar_list[0] as! PgAssetSource
    let assetId: String? = nilOrValue(pigeonVar_list[1])
    let url: String? = nilOrValue(pigeonVar_list[2])
    let mediaType: PgMediaType? = nilOrValue(pigeonVar_list[3])
    let videoUrl: String? = nilOrValue(pigeonVar_list[4])
    let duration: Double? = nilOrValue(pigeonVar_list[5])

    return PgAssetInput(
      type: type,
      assetId: assetId,
      url: url,
      mediaType: mediaType,
      videoUrl: videoUrl,
      duration: duration
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      assetId,
      url,
      mediaType,
      videoUrl,
      duration,
    ]
  }
}

/// previewAssets 的完整入参
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgPreviewRequest {
  var assets: [PgAssetInput]
  var initialIndex: Int64
  var sourceFrame: PgRect
  var selectedAssetIds: [String]
  var config: PgPickerConfig
  var showDownloadButton: Bool
  /// 空串 = 不额外建相册（iOS）/ 用 App 名（Android）
  var saveAlbumName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgPreviewRequest? {
    let assets = pigeonVar_list[0] as! [PgAssetInput]
    let initialIndex = pigeonVar_list[1] as! Int64
    let sourceFrame = pigeonVar_list[2] as! PgRect
    let selectedAssetIds = pigeonVar_list[3] as! [String]
    let config = pigeonVar_list[4] as! PgPickerConfig
    let showDownloadButton = pigeonVar_list[5] as! Bool
    let saveAlbumName = pigeonVar_list[6] as! String

    return PgPreviewRequest(
      assets: assets,
      initialIndex: initialIndex,
      sourceFrame: sourceFrame,
      selectedAssetIds: selectedAssetIds,
      config: config,
      showDownloadButton: showDownloadButton,
      saveAlbumName: saveAlbumName
    )
  }
  func toList() -> [Any?] {
    return [
      assets,
      initialIndex,
      sourceFrame,
      selectedAssetIds,
      config,
      showDownloadButton,
      saveAlbumName,
    ]
  }
}

/// 返回的单个媒体条目（对应公开的 [MediaItem]）
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgMediaItem {
  var assetId: String
  var mediaType: PgMediaType
  var thumbnailPath: String
  /// 秒，仅 video 有值
  var duration: Double? = nil
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgMediaItem? {
    let assetId = pigeonVar_list[0] as! String
    let mediaType = pigeonVar_list[1] as! PgMediaType
    let thumbnailPath = pigeonVar_list[2] as! String
    let duration: Double? = nilOrValue(pigeonVar_list[3])
    let width = pigeonVar_list[4] as! Int64
    let height = pigeonVar_list[5] as! Int64

    return PgMediaItem(
      assetId: assetId,
      mediaType: mediaType,
      thumbnailPath: thumbnailPath,
      duration: duration,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      assetId,
      mediaType,
      thumbnailPath,
      duration,
      width,
      height,
    ]
  }
}

/// pickAssets / previewAssets 的返回（对应公开的 [PickResult]）
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgPickResult {
  var items: [PgMediaItem]
  var isOriginalPhoto: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgPickResult? {
    let items = pigeonVar_list[0] as! [PgMediaItem]
    let isOriginalPhoto = pigeonVar_list[1] as! Bool

    return PgPickResult(
      items: items,
      isOriginalPhoto: isOriginalPhoto
    )
  }
  func toList() -> [Any?] {
    return [
      items,
      isOriginalPhoto,
    ]
  }
}

/// 保存网络图片的结果事件（对应公开的 [DownloadResult] sealed 家族）
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgDownloadResultEvent {
  var url: String
  var success: Bool
  /// 成功时的 assetId（Android: MediaStore URI；iOS: PHAsset localIdentifier）
  var assetId: String? = nil
  /// 失败时的错误码
  var errorCode: PgDownloadErrorCode? = nil
  /// 失败时的可读描述
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgDownloadResultEvent? {
    let url = pigeonVar_list[0] as! String
    let success = pigeonVar_list[1] as! Bool
    let assetId: String? = nilOrValue(pigeonVar_list[2])
    let errorCode: PgDownloadErrorCode? = nilOrValue(pigeonVar_list[3])
    let errorMessage: String? = nilOrValue(pigeonVar_list[4])

    return PgDownloadResultEvent(
      url: url,
      success: success,
      assetId: assetId,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      url,
      success,
      assetId,
      errorCode,
      errorMessage,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgPermissionStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgMediaFilter(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgMediaType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgAssetSource(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgExportFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgDownloadErrorCode(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return PgCropConfig.fromList(self.readValue() as! [Any?])
    case 136:
      return PgPickerConfig.fromList(self.readValue() as! [Any?])
    case 137:
      return PgRect.fromList(self.readValue() as! [Any?])
    case 138:
      return PgAssetInput.fromList(self.readValue() as! [Any?])
    case 139:
      return PgPreviewRequest.fromList(self.readValue() as! [Any?])
    case 140:
      return PgMediaItem.fromList(self.readValue() as! [Any?])
    case 141:
      return PgPickResult.fromList(self.readValue() as! [Any?])
    case 142:
      return PgDownloadResultEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PgPermissionStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgMediaFilter {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgMediaType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgAssetSource {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgExportFormat {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgDownloadErrorCode {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgCropConfig {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PgPickerConfig {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PgRect {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PgAssetInput {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PgPreviewRequest {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PgMediaItem {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? PgPickResult {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? PgDownloadResultEvent {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LivePhotoGalleryHostApi {
  /// 查询/申请相册权限
  func requestPermission(completion: @escaping (Result<PgPermissionStatus, Error>) -> Void)
  /// 打开相册选择器；返回 null 表示用户取消
  func pickAssets(config: PgPickerConfig, completion: @escaping (Result<PgPickResult?, Error>) -> Void)
  /// 预览资源列表（本地 & 网络混合）；返回 null 表示用户取消
  func previewAssets(request: PgPreviewRequest, completion: @escaping (Result<PgPickResult?, Error>) -> Void)
  /// 返回本地缩略图路径
  func getThumbnail(assetId: String, width: Double, height: Double, completion: @escaping (Result<String?, Error>) -> Void)
  /// 导出资源原文件到临时目录，返回本地路径
  func exportAsset(assetId: String, format: PgExportFormat, completion: @escaping (Result<String?, Error>) -> Void)
  /// 清理插件产生的临时文件
  func cleanupTempFiles(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LivePhotoGalleryHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LivePhotoGalleryHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LivePhotoGalleryHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 查询/申请相册权限
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        api.requestPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    /// 打开相册选择器；返回 null 表示用户取消
    let pickAssetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.pickAssets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickAssetsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! PgPickerConfig
        api.pickAssets(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickAssetsChannel.setMessageHandler(nil)
    }
    /// 预览资源列表（本地 & 网络混合）；返回 null 表示用户取消
    let previewAssetsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.previewAssets\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      previewAssetsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PgPreviewRequest
        api.previewAssets(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      previewAssetsChannel.setMessageHandler(nil)
    }
    /// 返回本地缩略图路径
    let getThumbnailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.getThumbnail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThumbnailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdArg = args[0] as! String
        let widthArg = args[1] as! Double
        let heightArg = args[2] as! Double
        api.getThumbnail(assetId: assetIdArg, width: widthArg, height: heightArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getThumbnailChannel.setMessageHandler(nil)
    }
    /// 导出资源原文件到临时目录，返回本地路径
    let exportAssetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.exportAsset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exportAssetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdArg = args[0] as! String
        let formatArg = args[1] as! PgExportFormat
        api.exportAsset(assetId: assetIdArg, format: formatArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      exportAssetChannel.setMessageHandler(nil)
    }
    /// 清理插件产生的临时文件
    let cleanupTempFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.cleanupTempFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cleanupTempFilesChannel.setMessageHandler { _, reply in
        api.cleanupTempFiles { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cleanupTempFilesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LivePhotoGalleryFlutterApiProtocol {
  /// 预览页保存网络图片完成（成功或失败）
  func onDownloadResult(event eventArg: PgDownloadResultEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 预览页下载进度（0.0 ~ 1.0）
  func onDownloadProgress(url urlArg: String, progress progressArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// 用户尝试超出最大选择数量
  func onMaxCountReached(maxCount maxCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LivePhotoGalleryFlutterApi: LivePhotoGalleryFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// 预览页保存网络图片完成（成功或失败）
  func onDownloadResult(event eventArg: PgDownloadResultEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 预览页下载进度（0.0 ~ 1.0）
  func onDownloadProgress(url urlArg: String, progress progressArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([urlArg, progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// 用户尝试超出最大选择数量
  func onMaxCountReached(maxCount maxCountArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onMaxCountReached\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([maxCountArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
