// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// 相册权限状态。门面层映射为公开的
/// `"authorized" | "limited" | "denied" | "notDetermined"` 字符串。
enum PgPermissionStatus {
  authorized,
  limited,
  denied,
  notDetermined,
}

/// 媒体类型过滤（对应公开的 [MediaFilter]）
enum PgMediaFilter {
  all,
  imageOnly,
  videoOnly,
  livePhotoOnly,
}

/// 单个媒体条目的类型（对应公开 API 的 `"image" | "video" | "livePhoto"`）
enum PgMediaType {
  image,
  video,
  livePhoto,
}

/// 预览资源来源（对应公开 API 的 `"local" | "network"`）
enum PgAssetSource {
  local,
  network,
}

/// 导出格式（对应公开 API 的 `"image" | "video" | "livePhotoVideo"`）
enum PgExportFormat {
  image,
  video,
  livePhotoVideo,
}

/// 保存网络图片失败的原因（对应公开的 [DownloadErrorCode]）。
/// 此前 Android 发 `"NETWORK_ERROR"` 字符串、iOS 发另一套、Dart 侧再 fromString，
/// 三处任意一处笔误都会静默退化成 `unknown`——改为枚举后是编译期错误。
enum PgDownloadErrorCode {
  permissionDenied,
  networkError,
  saveFailed,
  unknown,
}

/// 裁剪配置（对应公开的 [CropConfig]）
class PgCropConfig {
  PgCropConfig({
    required this.aspectRatioX,
    required this.aspectRatioY,
  });

  double aspectRatioX;

  double aspectRatioY;

  Object encode() {
    return <Object?>[
      aspectRatioX,
      aspectRatioY,
    ];
  }

  static PgCropConfig decode(Object result) {
    result as List<Object?>;
    return PgCropConfig(
      aspectRatioX: result[0]! as double,
      aspectRatioY: result[1]! as double,
    );
  }
}

/// 选择器配置（对应公开的 [PickerConfig]）
class PgPickerConfig {
  PgPickerConfig({
    required this.isDarkMode,
    required this.maxCount,
    required this.enableVideo,
    required this.enableLivePhoto,
    required this.showRadio,
    required this.autoPlayVideo,
    required this.maxVideoCount,
    required this.videoMaxDuration,
    required this.filterConfig,
    this.cropConfig,
  });

  bool isDarkMode;

  int maxCount;

  bool enableVideo;

  bool enableLivePhoto;

  bool showRadio;

  /// 视频进入预览页时是否自动播放（默认 false）
  bool autoPlayVideo;

  /// -1 = 无限制
  int maxVideoCount;

  /// 秒，0 = 无限制
  double videoMaxDuration;

  PgMediaFilter filterConfig;

  PgCropConfig? cropConfig;

  Object encode() {
    return <Object?>[
      isDarkMode,
      maxCount,
      enableVideo,
      enableLivePhoto,
      showRadio,
      autoPlayVideo,
      maxVideoCount,
      videoMaxDuration,
      filterConfig,
      cropConfig,
    ];
  }

  static PgPickerConfig decode(Object result) {
    result as List<Object?>;
    return PgPickerConfig(
      isDarkMode: result[0]! as bool,
      maxCount: result[1]! as int,
      enableVideo: result[2]! as bool,
      enableLivePhoto: result[3]! as bool,
      showRadio: result[4]! as bool,
      autoPlayVideo: result[5]! as bool,
      maxVideoCount: result[6]! as int,
      videoMaxDuration: result[7]! as double,
      filterConfig: result[8]! as PgMediaFilter,
      cropConfig: result[9] as PgCropConfig?,
    );
  }
}

/// 缩略图在屏幕中的位置（逻辑像素），用于飞入/飞回转场
class PgRect {
  PgRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  Object encode() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  static PgRect decode(Object result) {
    result as List<Object?>;
    return PgRect(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }
}

/// 传给 previewAssets 的单个资源（对应公开的 [AssetInput]）
class PgAssetInput {
  PgAssetInput({
    required this.type,
    this.assetId,
    this.url,
    this.mediaType,
    this.videoUrl,
    this.duration,
  });

  PgAssetSource type;

  String? assetId;

  String? url;

  PgMediaType? mediaType;

  String? videoUrl;

  /// 视频时长（秒）
  double? duration;

  Object encode() {
    return <Object?>[
      type,
      assetId,
      url,
      mediaType,
      videoUrl,
      duration,
    ];
  }

  static PgAssetInput decode(Object result) {
    result as List<Object?>;
    return PgAssetInput(
      type: result[0]! as PgAssetSource,
      assetId: result[1] as String?,
      url: result[2] as String?,
      mediaType: result[3] as PgMediaType?,
      videoUrl: result[4] as String?,
      duration: result[5] as double?,
    );
  }
}

/// previewAssets 的完整入参
class PgPreviewRequest {
  PgPreviewRequest({
    required this.assets,
    required this.initialIndex,
    required this.sourceFrame,
    required this.selectedAssetIds,
    required this.config,
    required this.showDownloadButton,
    required this.saveAlbumName,
  });

  List<PgAssetInput> assets;

  int initialIndex;

  PgRect sourceFrame;

  List<String> selectedAssetIds;

  PgPickerConfig config;

  bool showDownloadButton;

  /// 空串 = 不额外建相册（iOS）/ 用 App 名（Android）
  String saveAlbumName;

  Object encode() {
    return <Object?>[
      assets,
      initialIndex,
      sourceFrame,
      selectedAssetIds,
      config,
      showDownloadButton,
      saveAlbumName,
    ];
  }

  static PgPreviewRequest decode(Object result) {
    result as List<Object?>;
    return PgPreviewRequest(
      assets: (result[0] as List<Object?>?)!.cast<PgAssetInput>(),
      initialIndex: result[1]! as int,
      sourceFrame: result[2]! as PgRect,
      selectedAssetIds: (result[3] as List<Object?>?)!.cast<String>(),
      config: result[4]! as PgPickerConfig,
      showDownloadButton: result[5]! as bool,
      saveAlbumName: result[6]! as String,
    );
  }
}

/// 返回的单个媒体条目（对应公开的 [MediaItem]）
class PgMediaItem {
  PgMediaItem({
    required this.assetId,
    required this.mediaType,
    required this.thumbnailPath,
    this.duration,
    required this.width,
    required this.height,
  });

  String assetId;

  PgMediaType mediaType;

  String thumbnailPath;

  /// 秒，仅 video 有值
  double? duration;

  int width;

  int height;

  Object encode() {
    return <Object?>[
      assetId,
      mediaType,
      thumbnailPath,
      duration,
      width,
      height,
    ];
  }

  static PgMediaItem decode(Object result) {
    result as List<Object?>;
    return PgMediaItem(
      assetId: result[0]! as String,
      mediaType: result[1]! as PgMediaType,
      thumbnailPath: result[2]! as String,
      duration: result[3] as double?,
      width: result[4]! as int,
      height: result[5]! as int,
    );
  }
}

/// pickAssets / previewAssets 的返回（对应公开的 [PickResult]）
class PgPickResult {
  PgPickResult({
    required this.items,
    required this.isOriginalPhoto,
  });

  List<PgMediaItem> items;

  bool isOriginalPhoto;

  Object encode() {
    return <Object?>[
      items,
      isOriginalPhoto,
    ];
  }

  static PgPickResult decode(Object result) {
    result as List<Object?>;
    return PgPickResult(
      items: (result[0] as List<Object?>?)!.cast<PgMediaItem>(),
      isOriginalPhoto: result[1]! as bool,
    );
  }
}

/// 保存网络图片的结果事件（对应公开的 [DownloadResult] sealed 家族）
class PgDownloadResultEvent {
  PgDownloadResultEvent({
    required this.url,
    required this.success,
    this.assetId,
    this.errorCode,
    this.errorMessage,
  });

  String url;

  bool success;

  /// 成功时的 assetId（Android: MediaStore URI；iOS: PHAsset localIdentifier）
  String? assetId;

  /// 失败时的错误码
  PgDownloadErrorCode? errorCode;

  /// 失败时的可读描述
  String? errorMessage;

  Object encode() {
    return <Object?>[
      url,
      success,
      assetId,
      errorCode,
      errorMessage,
    ];
  }

  static PgDownloadResultEvent decode(Object result) {
    result as List<Object?>;
    return PgDownloadResultEvent(
      url: result[0]! as String,
      success: result[1]! as bool,
      assetId: result[2] as String?,
      errorCode: result[3] as PgDownloadErrorCode?,
      errorMessage: result[4] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PgPermissionStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PgMediaFilter) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PgMediaType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PgAssetSource) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PgExportFormat) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is PgDownloadErrorCode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is PgCropConfig) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PgPickerConfig) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PgRect) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is PgAssetInput) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is PgPreviewRequest) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is PgMediaItem) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is PgPickResult) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is PgDownloadResultEvent) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PgPermissionStatus.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PgMediaFilter.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PgMediaType.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PgAssetSource.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PgExportFormat.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PgDownloadErrorCode.values[value];
      case 135: 
        return PgCropConfig.decode(readValue(buffer)!);
      case 136: 
        return PgPickerConfig.decode(readValue(buffer)!);
      case 137: 
        return PgRect.decode(readValue(buffer)!);
      case 138: 
        return PgAssetInput.decode(readValue(buffer)!);
      case 139: 
        return PgPreviewRequest.decode(readValue(buffer)!);
      case 140: 
        return PgMediaItem.decode(readValue(buffer)!);
      case 141: 
        return PgPickResult.decode(readValue(buffer)!);
      case 142: 
        return PgDownloadResultEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class LivePhotoGalleryHostApi {
  /// Constructor for [LivePhotoGalleryHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LivePhotoGalleryHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 查询/申请相册权限
  Future<PgPermissionStatus> requestPermission() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.requestPermission$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PgPermissionStatus?)!;
    }
  }

  /// 打开相册选择器；返回 null 表示用户取消
  Future<PgPickResult?> pickAssets(PgPickerConfig config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.pickAssets$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PgPickResult?);
    }
  }

  /// 预览资源列表（本地 & 网络混合）；返回 null 表示用户取消
  Future<PgPickResult?> previewAssets(PgPreviewRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.previewAssets$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PgPickResult?);
    }
  }

  /// 返回本地缩略图路径
  Future<String?> getThumbnail(String assetId, double width, double height) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.getThumbnail$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[assetId, width, height]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// 导出资源原文件到临时目录，返回本地路径
  Future<String?> exportAsset(String assetId, PgExportFormat format) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.exportAsset$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[assetId, format]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// 清理插件产生的临时文件
  Future<void> cleanupTempFiles() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryHostApi.cleanupTempFiles$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class LivePhotoGalleryFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// 预览页保存网络图片完成（成功或失败）
  void onDownloadResult(PgDownloadResultEvent event);

  /// 预览页下载进度（0.0 ~ 1.0）
  void onDownloadProgress(String url, double progress);

  /// 用户尝试超出最大选择数量
  void onMaxCountReached(int maxCount);

  static void setUp(LivePhotoGalleryFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadResult$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadResult was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PgDownloadResultEvent? arg_event = (args[0] as PgDownloadResultEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadResult was null, expected non-null PgDownloadResultEvent.');
          try {
            api.onDownloadResult(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_url = (args[0] as String?);
          assert(arg_url != null,
              'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadProgress was null, expected non-null String.');
          final double? arg_progress = (args[1] as double?);
          assert(arg_progress != null,
              'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onDownloadProgress was null, expected non-null double.');
          try {
            api.onDownloadProgress(arg_url!, arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onMaxCountReached$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onMaxCountReached was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_maxCount = (args[0] as int?);
          assert(arg_maxCount != null,
              'Argument for dev.flutter.pigeon.live_photo_gallery.LivePhotoGalleryFlutterApi.onMaxCountReached was null, expected non-null int.');
          try {
            api.onMaxCountReached(arg_maxCount!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
